POST http://localhost:3333/auth/register
content-type: application/json

{
 "username":"Isaque",
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/auth/login
content-type: application/json

{
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/tasks
content-type: application/json
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI2Mzg4MDEsImV4cCI6MTc2MjY0OTYwMX0.Ax-BRfGjgCtbmPBgGHnzZW1a7L5lZxM9H4_IfbS5s-s

{
  "title":"Teste backend",
  "description":"KAKAKAKAK"
}