POST http://localhost:3333/auth/register
content-type: application/json

{
 "username":"Isaque",
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/auth/login
content-type: application/json

{
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/tasks
content-type: application/json
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI2NTAyMTIsImV4cCI6MTc2MjY2MTAxMn0._5uHBGCMy8wAU4gvmNzFhSVQMmsQhQflU-WVCUS6jtM

{
  "title":" A MAIS RECENTE",
  "description":"KAKAKAKAK"
}

###

GET http://localhost:3333/tasks?page=1&limit=22&orderBy=updateAt&completed=true
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI3NDE1OTIsImV4cCI6MTc2Mjc1MjM5Mn0.iL0x_o60jTHNeSsfRshg7zTNU_jUIJDkt2xdmKwYjsw
###

PATCH http://localhost:3333/tasks/019a65ed-0934-704e-a663-2703cd4c3788/complete
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI3NDE1OTIsImV4cCI6MTc2Mjc1MjM5Mn0.iL0x_o60jTHNeSsfRshg7zTNU_jUIJDkt2xdmKwYjsw
###

PATCH http://localhost:3333/tasks/019a65ed-0934-704e-a663-2703cd4c3788/incomplete
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI2OTcwMDcsImV4cCI6MTc2MjcwNzgwN30.6ToAQvqeRWGv-crcNZDFuSm57AsBb4XNIQwkqtf3lbU

###

PUT http://localhost:3333/tasks/019a65ed-0934-704e-a663-2703cd4c3788
content-type: application/json
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI3NDE1OTIsImV4cCI6MTc2Mjc1MjM5Mn0.iL0x_o60jTHNeSsfRshg7zTNU_jUIJDkt2xdmKwYjsw

{
  "title":" o famoso teste de update 2 parte ultimate",
  "description":"largatixa"
}

###

GET  http://localhost:3333/users/profile
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjMyMjcwODQsImV4cCI6MTc2MzIzNzg4NH0.fC9cXIHxuH2CYEnrtKuN8_ImBfnOngVZRq_Vc3xMvgc


###
PATCH http://localhost:3333/users/username
content-type: application/json
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI5Njg4MDUsImV4cCI6MTc2Mjk3OTYwNX0.u_pZ7FwbuTdiQS0IHZIANQJclFmeTNFL5AZMvdPM4oc

{
  "username": "O TADS"
}

###
PATCH http://localhost:3333/users/avatar
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI5OTEzMjAsImV4cCI6MTc2MzAwMjEyMH0.UCRQ4oJ4aH-tW6mgPKpYV2d_otKUuF3GTpNuwlw27U4