POST http://localhost:3333/auth/register
content-type: application/json

{
 "username":"Isaque",
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/auth/login
content-type: application/json

{
 "email":"isaque5@gmail.com",
 "password":"12345678"
}


###

POST http://localhost:3333/tasks
content-type: application/json
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI2NTAyMTIsImV4cCI6MTc2MjY2MTAxMn0._5uHBGCMy8wAU4gvmNzFhSVQMmsQhQflU-WVCUS6jtM

{
  "title":" A MAIS RECENTE",
  "description":"KAKAKAKAK"
}

###

GET http://localhost:3333/tasks?page=1&limit=22&completed=false
Authorization:Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhNjRmOS1hOWFlLTcyMTktYTdhYS00MGY0NjM5YTFhNjEiLCJpYXQiOjE3NjI2NTAyMTIsImV4cCI6MTc2MjY2MTAxMn0._5uHBGCMy8wAU4gvmNzFhSVQMmsQhQflU-WVCUS6jtM
